import { App } from '@capacitor/app';

/**
 * Handles automation intents generated by the AI
 */
export async function performNativeAction(rawTag: string) {
  if (typeof window === 'undefined') return;

  const tag = rawTag.trim();
  console.log("Processing native intent:", tag);

  // 1. CALL INTENT
  if (tag.startsWith('[CALL:')) {
    const target = tag.replace('[CALL:', '').replace(']', '').trim();
    // In a real app, we might search contacts, but for now we sanitize and dial
    const sanitized = target.replace(/[^\d+]/g, '');
    if (sanitized) {
      window.open(`tel:${sanitized}`, '_system');
    } else {
      // If it's a name, we'd need a contact plugin, but for the demo 
      // we'll just open the dialer
      window.open(`tel:`, '_system');
    }
    return;
  }

  // 2. OPEN APP INTENT
  if (tag.startsWith('[OPEN:')) {
    const appName = tag.replace('[OPEN:', '').replace(']', '').toLowerCase().trim();
    
    const appSchemes: Record<string, string> = {
      'whatsapp': 'whatsapp://',
      'youtube': 'youtube://',
      'maps': 'maps://',
      'google maps': 'comgooglemaps://',
      'camera': 'camera://',
      'facebook': 'fb://',
      'messenger': 'fb-messenger://',
      'facetime': 'facetime://'
    };

    const scheme = appSchemes[appName];
    if (scheme) {
      try {
        window.open(scheme, '_system');
      } catch (e) {
        console.error("Failed to launch app scheme:", scheme);
      }
    } else {
      // Fallback: try to search for the app or open in browser
      window.open(`https://www.google.com/search?q=open+${encodeURIComponent(appName)}+app`, '_system');
    }
  }
}

/**
 * Parses a message for native action tags and performs them.
 * This is usually called after the AI finishes speaking or streaming.
 */
export function processMessageIntents(content: string) {
  const callMatch = content.match(/\[CALL:[^\]]+\]/g);
  const openMatch = content.match(/\[OPEN:[^\]]+\]/g);

  if (callMatch) {
    callMatch.forEach(tag => performNativeAction(tag));
  }
  if (openMatch) {
    openMatch.forEach(tag => performNativeAction(tag));
  }
}
